#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 0.7.{build}
 
# branches to build
branches:
  # whitelist
  only:
    - master
    - FeatureSetup
 
# Do not build on tags (GitHub only)
skip_tags: false
 
#---------------------------------#
#    environment configuration  #
#---------------------------------#
 
# Operating system (build VM template)
os: Windows Server 2012
 
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
 
# clone directory
clone_folder: c:\projects\rtextnpp
 
# fetch repository as zip archive
#shallow_clone: true                 # default is "false"
 
# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

environment:
  COVERALLS_REPO_TOKEN:
    secure: ASvn2Aa6Q3wMScKIO6cMbzpzirZ0inBgBJsYkhS7uhXOtmM9EnnD20eBhtXi6NmP
  GIT_ACCESS_TOKEN:
    secure: +FR1WXoq1dCu2hQXBSk/kv9DBkII1QOJYeWOuGBL7aT1ZVpmohA13d0/hUClL7fy
  
# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
 
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#
 
# to add several platforms to build matrix:
platform:
  - x86
 
# to add several configurations to build matrix:
configuration:
  - Release
 
# scripts to run before build
before_build:
  nuget restore
 
#---------------------------------#
#       tests configuration       #
#---------------------------------#

build:
  parallel: true                  # enable MSBuild parallel builds
  project: RTextNpp.sln           # path to Visual Studio solution or project
 
  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed
  verbosity: minimal

# scripts to run after build
after_build:
  7z a Release.zip %APPVEYOR_BUILD_FOLDER%/RTextNpp/bin/x86/Release/RTextNpp.dll %APPVEYOR_BUILD_FOLDER%/RTextNpp.xml
  
artifacts:
  - path: Release.zip
    name: RTextNpp
  
# scripts to run after tests
after_test:
# generate report for NUnit testing framework:
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -excludebyattribute:"*.ExcludeFromCodeCoverage*" -skipautoprops -hideskipped:All -excludebyfile:*\*.il -filter:"-[RTextNpp]RTextNppPlugin.Properties -[RTextNpp]RTextNppPlugin.RText.Protocol* -[RTextNpp]RTextNppPlugin.DllExport* -[RTextNpp]RTextNppPlugin.Utilities.Npp* -[RTextNpp]RTextNppPlugin.Forms.ConsoleOutput* +[RTextNpp]RTextNppPlugin* +[RTextNpp]CSScriptIntellisense -[Tests]*" -target:"nunit-console-x86.exe" -targetargs:"/noshadow /nologo /labels /domain:single /framework:4.5 /nodots Tests\bin\x86\Release\Tests.dll" -output:coverage.xml
  - ps: .\CoverageFix.ps1
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

  
#---------------------------------#
#         notifications           #
#---------------------------------#
  
notifications:
 
  # Email
  - provider: Email
    to:
      - stefanos.anastasiou@esrlabs.com
    on_build_status_changed: true
    
  - provider: Slack
    auth_token:
      secure: AP0kOGkZK+gDtDw+fHl+SDc8Nk6sSqZ7o0ROHl9aR4ARw7ldK4KtGxGqiKp85SSH
    channel: automate-jep
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GIT_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "stefanos.anastasiou@esrlabs.com"
  - git config --global user.name "Stefanos Anastasiou"
#When clone depth is 1, origins are missing fix this issue here.
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch origin
  - git checkout -b master --track remotes/origin/master
  - git fetch --all
  - git remote show origin
  - git branch -a
  - git reset --hard %APPVEYOR_REPO_BRANCH%
  - git merge -m "Merging %APPVEYOR_REPO_BRANCH% commit %APPVEYOR_REPO_COMMIT% - %APPVEYOR_REPO_COMMIT_MESSAGE%" -s ours remotes/origin/%APPVEYOR_REPO_BRANCH%
  - git tag -a master/v%APPVEYOR_BUILD_VERSION%
  - ps: .\PushMasterTag.ps1
    
deploy:
  tag: v$(appveyor_build_version)
  release: RTextNpp-v$(appveyor_build_version)
  description: 'RTextNpp Release $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: +FR1WXoq1dCu2hQXBSk/kv9DBkII1QOJYeWOuGBL7aT1ZVpmohA13d0/hUClL7fy
  artifact: Release.zip            # upload Release as a single .zip file
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only