//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RTextNppPlugin.Properties {
    using System;
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTextNppPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _event {
            get {
                object obj = ResourceManager.GetObject("_event", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _modelError {
            get {
                object obj = ResourceManager.GetObject("_modelError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _modelNoErrors {
            get {
                object obj = ResourceManager.GetObject("_modelNoErrors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _namespace {
            get {
                object obj = ResourceManager.GetObject("_namespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Could not process request because backend is not running..
        /// </summary>
        internal static string CONNECTOR_INSTANCE_NULL {
            get {
                return ResourceManager.GetString("CONNECTOR_INSTANCE_NULL", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Backend is restarting....
        /// </summary>
        internal static string CONNECTOR_INSTANCE_NULL_DESC {
            get {
                return ResourceManager.GetString("CONNECTOR_INSTANCE_NULL_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConsoleIcon {
            get {
                object obj = ResourceManager.GetObject("ConsoleIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConsoleIconPng {
            get {
                object obj = ResourceManager.GetObject("ConsoleIconPng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap constructor {
            get {
                object obj = ResourceManager.GetObject("constructor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText backend service auto completion request failed..
        /// </summary>
        internal static string ERR_AUTO_COMPLETION_INVOKATION {
            get {
                return ResourceManager.GetString("ERR_AUTO_COMPLETION_INVOKATION", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Wrong invocation id return from backend! Please take a screenshot and contact support..
        /// </summary>
        internal static string ERR_AUTO_COMPLETION_INVOKATION_DESC {
            get {
                return ResourceManager.GetString("ERR_AUTO_COMPLETION_INVOKATION_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists please contact support..
        /// </summary>
        internal static string ERR_AUTO_COMPLETION_NULL_DESC {
            get {
                return ResourceManager.GetString("ERR_AUTO_COMPLETION_NULL_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText backend service auto completion request failed..
        /// </summary>
        internal static string ERR_AUTO_COMPLETION_NULL_RESP {
            get {
                return ResourceManager.GetString("ERR_AUTO_COMPLETION_NULL_RESP", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText backend is currently busy..
        /// </summary>
        internal static string ERR_BACKEND_BUSY {
            get {
                return ResourceManager.GetString("ERR_BACKEND_BUSY", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Please try again when the current command is executed. ( Status LED should be Green ).
        /// </summary>
        internal static string ERR_BACKEND_BUSY_DESC {
            get {
                return ResourceManager.GetString("ERR_BACKEND_BUSY_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection with RText backend..
        /// </summary>
        internal static string ERR_BACKEND_CONNECTING {
            get {
                return ResourceManager.GetString("ERR_BACKEND_CONNECTING", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists try to restart application or contact support..
        /// </summary>
        internal static string ERR_BACKEND_CONNECTING_DESC {
            get {
                return ResourceManager.GetString("ERR_BACKEND_CONNECTING_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText backend is not responding..
        /// </summary>
        internal static string ERR_BACKEND_NOT_RESPONDING {
            get {
                return ResourceManager.GetString("ERR_BACKEND_NOT_RESPONDING", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Please take a screenshot of the current console output and notify support..
        /// </summary>
        internal static string ERR_BACKEND_NOT_RESPONDING_DESC {
            get {
                return ResourceManager.GetString("ERR_BACKEND_NOT_RESPONDING_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText backend service reference link request failed..
        /// </summary>
        internal static string ERR_REF_LINK_NULL_RESPONSE {
            get {
                return ResourceManager.GetString("ERR_REF_LINK_NULL_RESPONSE", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists please contact support..
        /// </summary>
        internal static string ERR_REF_LINK_NULL_RESPONSE_DESC {
            get {
                return ResourceManager.GetString("ERR_REF_LINK_NULL_RESPONSE_DESC", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extension_method {
            get {
                object obj = ResourceManager.GetObject("extension_method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap field {
            get {
                object obj = ResourceManager.GetObject("field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap method {
            get {
                object obj = ResourceManager.GetObject("method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap namespace_add {
            get {
                object obj = ResourceManager.GetObject("namespace_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap property {
            get {
                object obj = ResourceManager.GetObject("property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rtext {
            get {
                object obj = ResourceManager.GetObject("rtext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RText++ output.
        /// </summary>
        internal static string RTEXT_OUTPUT_WINDOW_CAPTION {
            get {
                return ResourceManager.GetString("RTEXT_OUTPUT_WINDOW_CAPTION", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Change RText++ options....
        /// </summary>
        internal static string RTEXT_SHOW_OPTIONS_WINDOW {
            get {
                return ResourceManager.GetString("RTEXT_SHOW_OPTIONS_WINDOW", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide RText++ outline window.
        /// </summary>
        internal static string RTEXT_SHOW_OUTLINE_WINDOW {
            get {
                return ResourceManager.GetString("RTEXT_SHOW_OUTLINE_WINDOW", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide RText++ output window.
        /// </summary>
        internal static string RTEXT_SHOW_OUTPUT_WINDOW {
            get {
                return ResourceManager.GetString("RTEXT_SHOW_OUTPUT_WINDOW", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;appSettings&gt;
        ///        &lt;add key=&quot;ConsoleWindowActive&quot; value=&quot;True&quot; /&gt;
        ///        &lt;add key=&quot;AutoLoadWorkspace&quot; value=&quot;True&quot; /&gt;
        ///        &lt;add key=&quot;AutoSaveFiles&quot; value=&quot;True&quot; /&gt;
        ///        &lt;add key=&quot;AutoChangeWorkspace&quot; value=&quot;True&quot; /&gt;
        ///        &lt;add key=&quot;ExcludeExtensions&quot; value=&quot;meta;&quot; /&gt;
        ///    &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string RTextNpp_dll {
            get {
                return ResourceManager.GetString("RTextNpp_dll", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Show auto-complete list.
        /// </summary>
        internal static string SHOW_AUTO_COMPLETION_LIST_NAME {
            get {
                return ResourceManager.GetString("SHOW_AUTO_COMPLETION_LIST_NAME", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snippet {
            get {
                object obj = ResourceManager.GetObject("snippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unresolved {
            get {
                object obj = ResourceManager.GetObject("unresolved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}