//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tests.Properties {
    using System;
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to &lt;NotepadPlus&gt;
        ///    &lt;Languages&gt;
        ///        &lt;Language name=&quot;RTextNpp&quot; ext=&quot;atm&quot; commentStart=&quot;#&quot; /&gt;
        ///    &lt;/Languages&gt;
        ///    &lt;LexerStyles&gt;
        ///        &lt;LexerType name=&quot;RTextNpp&quot; desc=&quot;RText language file.&quot; ext=&quot;meta  atm40&quot; excluded=&quot;no&quot;&gt;
        ///            &lt;WordsStyle name=&quot;DEFAULT&quot; styleID=&quot;0&quot; fgColor=&quot;FFFFFF&quot; bgColor=&quot;3F3F3F&quot; fontName=&quot;&quot; fontStyle=&quot;0&quot; fontSize=&quot;&quot; /&gt;
        ///            &lt;WordsStyle name=&quot;COMMENT&quot; styleID=&quot;1&quot; fgColor=&quot;FF8000&quot; bgColor=&quot;3F3F3F&quot; fontName=&quot;&quot; fontStyle=&quot;3&quot; fontSize=&quot;&quot; /&gt;
        ///            &lt;WordsStyle nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RTextNpp {
            get {
                return ResourceManager.GetString("RTextNpp", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to *.atm:
        ///cmd /c automate-rtext-service -m 3.1.5 --ext-dir=Config/Automate/Extensions --macro-path=Config/Automate/Macros &quot;.&quot;.
        /// </summary>
        internal static string WorkspaceRoot {
            get {
                return ResourceManager.GetString("WorkspaceRoot", resourceCulture);
            }
        }
    }
}
